# Autostart applications
exec-once = waybar
exec-once = mako
exec-once = hyprpaper
exec-once = ~/.local/bin/wallpaper-theme.sh restore
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start pipewire pipewire-pulse wireplumber
exec-once = swayosd-server
exec-once = wl-paste --watch cliphist store
exec-once = remmina -i
exec-once = telegram-desktop -startintray
exec-once = discord --start-minimized
exec-once = udiskie --automount --notify --tray
exec-once = hypridle
