general {
    lock_cmd = hyprctl dispatch dpms off
    unlock_cmd = hyprctl dispatch dpms on
}

# Dim screen after 2 minutes
listener {
    timeout = 120
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Screen off after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
